### ISSUE TITLE
Adding 2001: A Space Odyssey (1968)

### ISSUE THREAD

**Issue by cdrrazan** [k4m4/movies-for-hackers#170]
Although Space odyssey is great sci-fi space movie but connection like HAL 9000 could make it into this list although I haven't forked the repo for this. Would like to know your view in this.

**Comment by k4m4** [comment]
Hi there @cdrrazan. I believe that HAL 9000 should definitely make it into this list.

**Comment by cdrrazan** [comment]
Thank you chief. This is definitely for HAL 9000
