### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by j-roc** [k4m4/movies-for-hackers#174]
Just curious, I see a lot of PRs and issues that have media that should be added to the list. I might have to start a fork of my own, I guess.

**Comment by k4m4** [comment]
Hi there. Thank you for taking the time to open this issue. As for the question you are posing: no, the project is not dead. If you have a look at the contribution guidelines of the repo, contributions are initially given an `endorsement-needed` tag and will be included in the curated list if they are endorsed by the community (hence the number of open issues/PRs). You can read more about the endorsement process in the [contributing.md](https://github.com/k4m4/movies-for-hackers/blob/master/contributing.md) file. Finally, forks of this project are always more than welcome. I hope that I have answered you question. Thanks again.
