### ISSUE TITLE
Source Code should not be on the list

### ISSUE THREAD

**Issue by ccoenen** [k4m4/movies-for-hackers#177]
I have been misguided by the title years ago. This movie is not a bad movie, but it has - in my opinion - nothing to do with programming, hacking, hacker culture or similar topics.

If you disagree, feel free to close this issue, no need for discussion. This is your list, not mine!

**Comment by styfle** [comment]
💯 agree

**Comment by j-roc** [comment]
Agreed, I enjoyed the movie felt it was an interesting bit of scifi film, it has nothing really to do with hackers.
