### ISSUE TITLE
Fix existing link which breaks CI tests for new PRs

### ISSUE THREAD

**Issue by jenni** [k4m4/movies-for-hackers#218]
CI tests are failing on new PRs because `https://saythanks.io/to/k4m4` is broken.

```
Issues :-(
> Links 
  1. [L010]  https://saythanks.io/to/k4m4 getaddrinfo: Name or service not known
```

**Comment by k4m4** [comment]
Hi @jenni. Thanks for bringing this up. Following up on this [here](https://github.com/BlitzKraft/saythanks.io/issues/60).
