### ISSUE TITLE
Who's rating this?

### ISSUE THREAD

**Issue by roberto-morado** [k4m4/movies-for-hackers#290]

**Comment by StellarStoic** [comment]
this should give you the answer @roberto-morado https://help.imdb.com/article/imdb/track-movies-tv/ratings-faq/G67Y87TFYYP6TWAV

**Comment by roberto-morado** [comment]
Oh, I see what's going on; would the community be interested on a customized voting system? This will allow us to rank the movies ourselves.

**Comment by StellarStoic** [comment]
Why? IMDB has a lot of voters and it's completely reliable. Why recreating something that works?

**Comment by roberto-morado** [comment]
Right
