### ISSUE TITLE
[feature request] Include TV shows as well

### ISSUE THREAD

**Issue by lakshaykalbhor** [k4m4/movies-for-hackers#33]
There are many tv series such as Silicon Valley, etc that are great and hackers would love to watch them. I suggest that a new column be made for TV shows.

**Comment by keyserfaty** [comment]
Halt and Catch Fire should be on that list!

**Comment by lakshaykalbhor** [comment]
I love halt and catch fire. There are many more such as : Mr Robot, etc. It would be great if we could have a column for tv shows.

**Comment by superfunkminister** [comment]
+1!

**Comment by robertojrojas** [comment]
+1   These shows come to mind Person of Interest, Black Mirror, and Dark Net.

**Comment by alsoknownasdrew** [comment]
+1

**Comment by spartanatreyu** [comment]
[Mr Robot](https://www.youtube.com/watch?v=xIBiJ_SzJTA) has more to do with hacking than most of the movies already on the list.

I can't take this list as anything more than meh at the moment.

Black Mirror could also be included, less actual hacking and more social impact of technology but still potentially worthy of the list.

**Comment by lakshaykalbhor** [comment]
@k4m4 
What's the status? Will TV shows be added to the list or not?

**Comment by k4m4** [comment]
TV Shows section has been added. Thanks! 
@lakshaykalbhor
