### ISSUE TITLE
Movie request: "Colossus: The Forbin Project"

### ISSUE THREAD

**Issue by jtrascap** [k4m4/movies-for-hackers#34]
It's and older movie and so some might giggle looking at the then-state-of-the-art hardware, but the language and science is pretty much on target, and its a really engaging frankensteins-like thriller. very well respected - but if you go looking on youtube beware the Trailers From Hell John Landis video where he gives it all away.

**Comment by j-roc** [comment]
This is probably the original (and one of the best) 'hacker' movies, endorsed.
