### ISSUE TITLE
Mr. Robot

### ISSUE THREAD

**Issue by kinari-01** [k4m4/movies-for-hackers#36]
Is there any reason Mr. Robot is missing? Is it too popular?
I think it's one of the best.

**Comment by markusdanek** [comment]
This repository is about movies and not tv shows. Thats the reason why it is missing :)

**Comment by kinari-01** [comment]
Oh, I see, that makes sense, thank you!
I think the distinction between those became smaller in the last decade, though.

**Comment by MrS0m30n3** [comment]
There is already an open pull-request: https://github.com/k4m4/movies-for-hackers/pull/10
