### ISSUE TITLE
Brazil by Terry Gilliam 

### ISSUE THREAD

**Issue by gildo** [k4m4/movies-for-hackers#54]
I don't see one of the most important films for the hacker culture, **Brazil** by the awesome _Terry Gilliam_  

[Wikipedia](https://en.wikipedia.org/wiki/Brazil_%281985_film%29)
[Slashdot](http://m.slashdot.org/story/11020)

**Comment by smonff** [comment]
Brazil is surely one of the best Orwell's 1984 adaptation.
