### ISSUE TITLE
Please add "Johnny Mnemonic" to "SciFI"

### ISSUE THREAD

**Issue by nbartels** [k4m4/movies-for-hackers#90]
> A data courier, literally carrying a data package inside his head, must deliver it before he dies from the burden or is killed by the Yakuza.

http://www.imdb.com/title/tt0113481/

IMDB Rating: 5.6

**Comment by nbartels** [comment]
It's a duplicate, sry

**Comment by k4m4** [comment]
No problem. Thank you for your suggestion. :)
