### ISSUE TITLE
Well thank you!

### ISSUE THREAD

**Issue by lirantal** [k4m4/movies-for-hackers#96]
You are so selfish!
Thank you for ruining my weekends.
Thank you for consuming my open source work time with this great movies compilation.

![Thanks](http://i.giphy.com/TUtr2Ky56D4Zy.gif)

But seriously, great list.
Thanks for opening this repo it's a great idea! :-)

**Comment by k4m4** [comment]
Thank you for your support buddy! I really appreciate it!
Glad you liked this repo. :))
