### ISSUE TITLE
Please add "You are wanted" to "TV Series"

### ISSUE THREAD

**Issue by nbartels** [k4m4/movies-for-hackers#99]
> Lukas Franke (Matthias Schweighöfer) is the victim of a cyber-crime attack. All his personal data, web and social media profiles get hacked and he gets accused of being involved in eco-terrorism. Lukas struggles to prove that he is innocent. His family, friends and colleagues doubt his innocence and start suspecting him. Lukas tries to find out who is behind the cyber-attacks and finds another victim, Lena Arandt, with whom he tries to solve the situation. Together they find out that someone from the German BKA (Federal Criminal Police) pulls the strings behind this crime.

http://www.imdb.com/title/tt5462886/

Imdb Rating: starts on March 17, 2017

**Comment by k4m4** [comment]
Added. Thank you for your contribution. :)
@nbartels
